export const NEXT_PUBLIC_VHIGH_AVATAR_GEN_0_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_VHIGH_AVATAR_GEN_0_CONTRACT_ADDRESS || "";
export const NEXT_PUBLIC_VERCEL_ENV = process.env.NEXT_PUBLIC_VERCEL_ENV || "";
export const NEXT_PUBLIC_IPFS_CID = process.env.NEXT_PUBLIC_IPFS_CID || "";
